name: Update HTML from Google Sheet

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * 0'   # every Sunday at 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # ensures checkout uses write-access token

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Generate HTML
        run: python notes/generate_html.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Update notes' index.html from Google Sheet" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF}
